FROM maven:3.6.3-jdk-11 AS builder

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN mvn clean install -DskipTests

WORKDIR /usr/src/app/catalog_service
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim

COPY --from=builder /usr/src/app/catalog_service/target/catalog_service-1.0-SNAPSHOT.jar /app/catalog_service.jar
COPY --from=builder /usr/src/app/catalog_service/data /app/data
WORKDIR /app

EXPOSE 8081

CMD ["java", "-jar", "catalog_service.jar"]

