FROM maven:3.6.3-jdk-11 AS builder

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN mvn clean install -DskipTests

WORKDIR /usr/src/app/front_tier
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim

COPY --from=builder /usr/src/app/front_tier/target/front_tier-1.0-SNAPSHOT.jar /app/front_tier.jar

WORKDIR /app

EXPOSE 1218

CMD ["java", "-jar", "front_tier.jar"]

